config/routes.rb
Matchups::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  match "/users", :to => "users#index"
  match "/tip/:id/like", :to => "tips#like", :as => "like"
  match "/characters", :to => "characters#index"
  match "/characters/:name", :to => "characters#show", :as => :character_show
  match "/characters/:player/vs:opponent", :to => "search#tips", :as => :tip_search
  match "/search", :to => "search#input", :as => :search
  match "/stream", :to => "pages#stream"
  match "/", :to => "pages#homepage"

  resources :blogs
  resources :feedbacks
  resources :tips

  root :to => "pages#homepage"
end

app/models/article.rb
class Tip < ActiveRecord::Base
 belongs_to :user
 belongs_to :matchup
 has_many :likes


 def count_likes
   unless self.like_count
    return 0
   else
     self.like_count
   end
 end


end

app/models/blog.rb
class Blog < ActiveRecord::Base
end

app/models/character.rb
class Character < ActiveRecord::Base

  def <=>(b)
    self.created_at <=> b.created_at
  end

  def self.character_list
   [ 'Ryu','Ken','E Honda','Ibuki','Makoto','Dudley','Seth','Gouken','Akuma','Gen','Dan','Sakura','Oni',
     'Yun','Juri','Chun Li','Dhalsim','Abel','C Viper','M Bison','Sagat','Cammy','Dee Jay','Cody','Guy','Hakan','Yang',
    'Evil Ryu','Guile','Blanka','Zangief','Rufus','El Fuerte','Vega','Balrog','Fei Long','T Hawk','Adon','Rose'
    ]
  end

end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
  
  validates_presence_of :body

end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :tip
end

app/models/tip.rb
class Tip < ActiveRecord::Base
 validates_presence_of :body
 belongs_to :user
 belongs_to :matchup
 has_many :likes


 def count_likes
   unless self.like_count
    return 0
   else
     self.like_count
   end
 end


end

app/models/user.rb
class User < ActiveRecord::Base
  validates_uniqueness_of :name
  has_many :tips

  # Include default devise modules. Others available are:
  # :token_authenticatable, :lockable, :timeoutable and :activatable
  devise :database_authenticatable, :registerable,:omniauthable,
         :recoverable, :rememberable, :trackable, :validatable
  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :name



   def self.find_for_facebook_oauth(access_token, signed_in_resource=nil)
    data = access_token['extra']['user_hash']
    if user = User.find_by_email(data["email"])
      user
    else # Create an user with a stub password. 
      User.create!(:email => data["email"], :name => data["name"], :password => Devise.friendly_token[0,20]) 
    end
  end 
  
  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["user_hash"]
        user.email = data["email"]
      end
    end
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  expose(:feedback) { Feedback.new }
  expose(:randomTips) { Tip.find(:all, :order => "RANDOM()", :limit => 2) } 
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  expose(:blog)
  expose(:blogs) { Blog.order("created_at desc").limit(10) }

  def create
    if blog.save
      redirect_to blog, :notice => 'Blog was successfully created.'
    else
      render :action => "new", :notice => blog.errors
    end
  end

  def update
    if blog.update_attributes(params[:blog])
      flash[:success] = 'Blog updated'
      redirect_to blog_path(blog)
    else
      render :action => "edit"
    end
  end

  def destroy
    blog.destroy
    redirect_to :back
  end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  expose(:characters) { Character.character_list } 
  expose(:character) { params[:name] }
  expose(:tips) { Tip.order("created_at desc").limit(5) }
  expose(:characterTips) { Tip.where(:player => character) }
  expose(:characterNames) { Character.character_list.sort! }
  expose(:opponentTips) { Tip.where(:opponent => character) }

end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  expose(:feedback)
  expose(:feedbacks) { Feedback.all }

  def create
    if current_user
      feedback.referer = current_user.name
    else
      feedback.referer = "Guest"
    end
    if feedback.save
      redirect_to :back, :notice => '>> Thanks for the Feedback! <<'
    else
      redirect_to :back, :notice => feedback.errors
    end
  end

  def destroy
    feedback.destroy
    redirect_to :back
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  expose(:blogs) { Blog.order("created_at desc").limit(3) }
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  expose(:character) { params[:player] }
  expose(:characterNames) { Character.character_list.sort! }
  expose(:opponentTips) { Tip.where(:opponent => character) }

  # Takes the input of the "/:search" url and re-directs to the corresponding URL.
  def input
    if params[:player] && params[:opponent]
      redirect_to tip_search_path(params[:player], params[:opponent])
    else
      redirect_to "/"
    end
  end

  # This brings specific matchup tips to the top of the tip/search query
  def tips
    all_tips = Tip.where(:player => params[:player])
    opponent_tips = Tip.where(:player => character, :opponent => params[:opponent])
    @searchTips = opponent_tips + (all_tips - opponent_tips)
  end

end

app/controllers/tips_controller.rb
class TipsController < ApplicationController
  expose(:tips) { Tip.all }
  expose(:matchup)
  expose(:tip)
  expose(:characterTips) { Tip.where(:player => tip.player, :opponent => tip.opponent).reject { |x| x == tip } }
  expose(:characterNames) { Character.character_list.sort! }

  def new
    session[:return_to] = request.referer
  end

  def create
    if current_user
      tip.user_id = current_user.id
      if tip.save
        redirect_to session[:return_to], :notice => 'Thanks for the tip.'
      else
        render :action => 'new', :notice => tip.errors
      end
    else
      redirect_to session[:return_to], :notice => 'You have to be logged in to add tips!'
    end
  end

  def update
    if tip.update_attributes(params[:tip])
      flash[:success] = 'Tip updated'
      redirect_to matchup_path(tip.matchup)
    else
      render :action => "edit"
    end
  end

  def destroy
    tip.destroy
    redirect_to :back
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController


  def facebook
    # You need to implement the method below in your model
    @user = User.find_for_facebook_oauth(env["omniauth.auth"], current_user)

    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Facebook"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.facebook_data"] = env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  expose(:users) { User.all }
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/views/blogs/_form.html.erb
<%= form_for(@blog) do |f| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blogs/edit.haml
%h1 Editing blog
- form_for blog do |o|
  %p
    = o.label :title
    %br
    = o.text_field :title
  %p
    = o.label :body
    = o.text_area :body
  %p
    = o.label :image_url
    %br
    = o.text_field :image_url
  = o.submit "Submit", :action => :create, :class => :button, :style => 'float: right'
  = link_to 'Show', blog_path(o)
  = link_to 'Back', blogs_path(o)

app/views/blogs/index.haml
#blog
  - if current_user && current_user.admin
    = link_to 'New Blog', new_blog_path, :class => :button, :style => "float: right; clear:both; background: black; color: white"
  %ul
    - blogs.each do |blog|
      %li
        - if current_user && current_user.admin
          = link_to 'Edit', edit_blog_path(blog)
          |
          = button_to "Delete", blog_path(blog), :method => :delete, :confirm => "Yea?"
        %h2= link_to blog.title, blog_path(blog)
        #blogContent
          = link_to image_tag("../img/#{blog.image_url}"), blog_path(blog)
          %p= raw truncate(blog.body, :length => 350, :omission => '........')
#comments
  <div id="fb-root"></div><script src="http://connect.facebook.net/en_US/all.js#xfbml=1"></script><fb:comments href="matchuptips.com" num_posts="5" width="550"></fb:comments>

app/views/blogs/new.haml
#blog
  %h2 New Blog
  - form_for blog do |o|
    %p
      = o.label :title
      %br
      = o.text_field :title
    %p
      = o.label :body
      = o.text_area :body
    %p
      = o.label :image_url
      %br
      = o.text_field :image_url
    = o.submit "Submit", :action => :create, :class => :button

app/views/blogs/show.haml
#blogShow
  %h2= blog.title
  #blogContent
    = link_to image_tag("../img/#{blog.image_url}"), blog_path(blog)
    %p= raw blog.body
#comments
  %h2 Comments
  %hr
  <div id="fb-root"></div><script src="http://connect.facebook.net/en_US/all.js#xfbml=1"></script><fb:comments href="matchuptips.com/blog/#{blog.id}" num_posts="5" width="550"></fb:comments>

app/views/characters/_form.haml
- form_for([character, combo_tip]) do |o|
  = o.text_area :body
  = o.submit "Submit", :action => :create

app/views/characters/index.haml
= image_tag("/img/sf4logo.jpg")
%h2 Select a character!
#chooseYourCharacter
  %ul
    - characters.each do |character|
      - if character == "Yang"
        %li
          = link_to image_tag("../img/characters/#{character.humanize.titleize}.jpg"), character_show_path(character.humanize.titleize)
      - elsif character == "Yun"
        %br
        %li
          = link_to image_tag("../img/characters/#{character.humanize.titleize}.jpg"), character_show_path(character.humanize.titleize)
      - elsif character == "Ryu"
        %li{:style => "margin-left: 25px"}
          = link_to image_tag("../img/characters/#{character.humanize.titleize}.jpg"), character_show_path(character.humanize.titleize)
      - elsif character == "Evil Ryu"
        %br
        %li{:style => "margin-left: 40px"}
          = link_to image_tag("../img/characters/#{character.humanize.titleize}.jpg"), character_show_path(character.humanize.titleize)
      - else
        %li
          = link_to image_tag("../img/characters/#{character.humanize.titleize}.jpg"), character_show_path(character.humanize.titleize)


        

app/views/characters/show.haml
%h1
  =image_tag("/img/characters/#{character}.jpg")
  = character
%h2
  - form_tag (search_path, :multipart => true) do
    = select_tag("player", options_for_select(characterNames, character))
    vs
    = select_tag("opponent", options_for_select(characterNames, params[:opponent]))
    = submit_tag "Go", :class => :button

- unless characterTips.empty?
  %ul.tips
    - characterTips.each do |tip|
      %li
        = link_to image_tag("../img/characters/#{tip.opponent}.jpg"), character_show_path(tip.opponent)
        %h2
          = link_to tip.player, tip_path(tip)
          VS
          = link_to tip.opponent, tip_path(tip)
        #tipContent
          %p=link_to truncate(tip.body, :length => 150, :omission => "....."), tip_path(tip)
          %p
            = tip.user.name
            = ':'
            = time_ago_in_words(tip.created_at)
            ago
- else
  %br
  %h3 Oh, it looks like there aren't any tips yet!
  %p Got a tip? Be the first one to add a tip here!
  = link_to 'Add a tip', new_tip_path, :class => :button
- unless opponentTips.empty?
  %h2{ :style => "margin: 2em auto" } What are your opponents up to?
  %ul.tips
    - opponentTips.each do |tip|
      %li
        = link_to image_tag("../img/characters/#{tip.player}.jpg"), character_show_path(tip.player)
        %h2
          = link_to tip.player, character_show_path(tip.player)
          VS
          = link_to tip.opponent, character_show_path(tip.opponent)
        #tipContent
          %p=link_to truncate(tip.body, :length => 150, :omission => "....."), tip_path(tip)
          %p
            = tip.user.name
            = ':'
            = time_ago_in_words(tip.created_at)
            ago

app/views/feedbacks/index.haml
- if current_user && current_user.admin?
  %h2 Matchup: Feedback List
  %hr
  #feedback
    %ul
      - feedbacks.each do |feedback|
        %li
          %h3
            %b= feedback.referer
            = button_to "Remove", feedback_path(feedback), :method => :delete, :style => "float: right;"
            (
            = feedback.created_at.to_date
            )
          %p
            = feedback.body
- else
  %h2 Your not an admin!

app/views/feedbacks/new.haml
%h1 Submit Feedback
%h2 Choose Kind
%ul
  %li Bug
  %li Idea
  %li Praise
%p
  %b Choose Kind:
  %i Text Area

app/views/layouts/_adminSidebar.haml
-if current_user && current_user.admin
  %h2 Admin
  %ul
    %li= link_to "Users", users_path
    %li= link_to "Posts", '/tips'
    %li= link_to "Feedback", feedbacks_path

app/views/layouts/_breadcrum.haml
%ul
  %li
    %a{:href => "/"}> Super Street Fighter 4
    \&nbsp;&nbsp;/&nbsp;&nbsp;

app/views/layouts/_copywrap.haml
© 2011
%strong Matchuptips.com all rights reserved.
- if Rails.env.production?
  :javascript
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-19817143-1']);
    _gaq.push(['_trackPageview']);
    (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

app/views/layouts/_nav.haml
#nav
  #logo
    = link_to image_tag("/img/matchupslogo.png"), "/"
  #user
    - if user_signed_in?
      #facebookLoggedIn
        = image_tag("../img/facebook-button-logo.png")
        .name= current_user.name
      #signOut= link_to " Sign Out", "/users/sign_out"
    - else
      #facebookLoggedIn
        = image_tag("../img/facebook-button-logo.png")
        .name= link_to "Login with Facebook", user_omniauth_authorize_path(:facebook)

app/views/layouts/_secondaryNav.haml
#secondaryNav
  %ul
    %li= link_to "Homepage", root_path
    %li= link_to "Tips", characters_path
    %li= link_to "Blogs", blogs_path
    %li= link_to "Stream", stream_path

app/views/layouts/_sidebar.haml
#sidebarSection
  #alternating
    %h3 Matchuptips.com ~ Facebook
    #facebookLike
      <iframe src="http://www.facebook.com/plugins/like.php?href=matchuptips.com&amp;send=false&amp;layout=standard&amp;width=240&amp;show_faces=true&amp;action=like&amp;colorscheme=light&amp;font&amp;height=80" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:240px; height:80px;" allowTransparency="true"></iframe>
#sidebarSection
  #tipSubmit
    %h3 Got a tip?
    %p Don't hold out on us! Share the goods. Its easy! 
    = link_to "Add a tip", new_tip_path, :class => :button
#sidebarSection
  #alternating
    %h3 Random Tips
    - unless randomTips.empty?
      %ul.tipsRandom
        - randomTips.each do |tip|
          %li
            =link_to image_tag("../img/characters/#{tip.player}.jpg"), tip_path(tip)
            Vs
            =link_to image_tag("../img/characters/#{tip.opponent}.jpg"), tip_path(tip)
            %h4
              .spacer=link_to tip.player, tip_path(tip)
              .spacer=link_to tip.opponent, tip_path(tip)
            %p=link_to truncate(tip.body, :length => 45, :omission => "..."), tip_path(tip)
#sidebarSection
  #sidebarFeedback
    %h3 Feedback?
    - form_for(feedback) do |o|
      = o.text_area :body
      %p
        = o.submit "Submit", :controller => :feedbacks, :action => :create, :class => :button

app/views/layouts/application.haml
%html
  %head
    %meta{'name' => "description", :content => 'Learn and share Super Street fighter 4 match tips.'}/
    %meta{'name' => "keywords", :content => 'Super Street Fighter 4, vs, versus, how to beat, matchups'}/
    %meta{'property' => 'fb:admins', :content => '500705660'}/
    %title 
      - if params[:id] && defined? tip
        = "#{tip.player} vs #{tip.opponent} tips | Super Street Fighter 4 match tips | matchuptips.com"
      - elsif params[:id] && defined? character
        = "#{character.name} tips. Super Street Fighter 4 match tips | matchuptips.com "
      - else
        Super Street Fighter 4 match tips | matchuptips.com
    = csrf_meta_tag
    = stylesheet_link_tag 'global.css', :rel => 'stylesheet', :type => 'text/css'
    = javascript_include_tag 'jquery', 'jquery-ui', 'application'
  %body
    #wrapper
      #topbar
        = render :partial => '/layouts/nav'
        = render :partial => '/layouts/secondaryNav'
      #adminSidebar
        = render :partial => '/layouts/adminSidebar'
      #contentContainer
        #midsection
          #content
            #messages
              - if flash.any?
                =  flash[:notice]
                = flash[:failure]
                = flash[:success]
            = yield 
          #sidebar
            = render :partial => '/layouts/sidebar'
      #footer
        = render :partial => '/layouts/footer'
      #copywrap
        = render :partial => '/layouts/copywrap'

app/views/pages/homepage.haml
#blog
  %ul
    - blogs.each do |blog|
      %li
        %h2= link_to blog.title, blog_path(blog)
        #blogContent
          = link_to image_tag("../img/#{blog.image_url}"), blog_path(blog)
          %p= raw truncate(blog.body, :length => 350, :omission => '........')
#comments
  <div id="fb-root"></div><script src="http://connect.facebook.net/en_US/all.js#xfbml=1"></script><fb:comments href="matchuptips.com" num_posts="5" width="550"></fb:comments>

app/views/pages/stream.haml
%h2 The Stream
%p The stream is brough to you every Friday starting around 6.
%p Matches are held in State College Pa. Check out the Srk forums for the scoop on the State College crew.
<object type="application/x-shockwave-flash" height ="500" width="600" id="jtv_flash" data="http://www.justin.tv/widgets/live_embed_player.swf?start_volume=0.5&amp;backgroundImage=&amp;channel=wakkwakk&amp;hostname=www.justin.tv&amp;auto_play=false" bgcolor="#000000">    <param name="allowFullScreen" value="true" />    <param name="allowScriptAccess" value="always" />    <param name="allowNetworking" value="all" />    <param name="movie" value="http://www.justin.tv/widgets/live_embed_player.swf" />    <param name="flashvars" value="start_volume=0.5&amp;backgroundImage=&amp;channel=wakkwakk&amp;hostname=www.justin.tv&amp;auto_play=false" /></object><br /><a href="http://www.justin.tv/wakkwakk#r=-rid-&amp;s=em" style="padding:2px 0px 4px; display:block; width:353; font-weight:normal; font-size:10px; text-decoration:underline; text-align:center;">Watch live video from wakkwakk on www.justin.tv</a>
<div id="fb-root"></div><script src="http://connect.facebook.net/en_US/all.js#xfbml=1"></script><fb:comments href="matchuptips.com/stream" num_posts="5" width="550"></fb:comments>

app/views/search/tips.haml
%h1
  =image_tag("/img/characters/#{character}.jpg")
  = character
%h2
  - form_tag (search_path, :multipart => true) do
    = select_tag("player", options_for_select(characterNames, params[:player]))
    vs
    = select_tag("opponent", options_for_select(characterNames, params[:opponent]))
    = submit_tag "Go", :class => :button
- unless @searchTips.empty?
  %ul.tips
    - @searchTips.each do |tip|
      %li
        = link_to image_tag("../img/characters/#{tip.opponent}.jpg"), character_show_path(tip.opponent)
        %h2
          = link_to tip.player, tip_path(tip)
          VS
          = link_to tip.opponent, tip_path(tip)
        #tipContent
          %p=link_to truncate(tip.body, :length => 150, :omission => "....."), tip_path(tip)
          %p
            = tip.user.name
            = ':'
            = time_ago_in_words(tip.created_at)
            ago
- else
  %br
  %h3 No tips yet? Got one? Be the first and and add a tip!
  = link_to 'Add a tip', new_tip_path, :class => :button
- unless opponentTips.empty?
  %h2{ :style => "margin: 2em auto" } What are your opponents up to?
  %ul.tips
    - opponentTips.each do |tip|
      %li
        = link_to image_tag("../img/characters/#{tip.player}.jpg"), character_show_path(tip.player)
        %h2
          = link_to tip.player, character_show_path(tip.player)
          VS
          = link_to tip.opponent, character_show_path(tip.opponent)
        #tipContent
          %p=link_to truncate(tip.body, :length => 150, :omission => "....."), tip_path(tip)
          %p
            = tip.user.name
            = ':'
            = time_ago_in_words(tip.created_at)
            ago

app/views/tips/edit.haml
%h1
  = image_tag("../img/characters/#{matchup.player.name}.jpg")
  = matchup.player.name
  Vs
  = matchup.opponent.name
  = image_tag("../img/characters/#{matchup.opponent.name}.jpg")

- form_for ([matchup, tip]) do |article|
  %p
    = tip.body
  %br
    = article.label :Body
    = article.text_area :body
    = article.submit 'Update', :action => :update

app/views/tips/index.haml
- if current_user && current_user.admin
  %h1 Recent Posts
  %h2= tips.count
  %ul
  - tips.each do |tip|
    - unless tip.body == nil
      %li
        %hr
        %h3
          = tip.player
          vs
          = tip.opponent
        = raw(tip.body)
        = tip.user.name
        = button_to "Delete", tip_path( tip), :method => :delete
- else
  %h2
    Hey Your not an Admin!

app/views/tips/new.haml
#addTip
  %h1 Share a tip
  %br
  - unless current_user
    %p 
      In order to add a tip you need to log into facebook.
    = link_to "Login to Facebook.", user_omniauth_authorize_path(:facebook), :class => :button
  - else
    - form_for tip do |o|
      %h2
        = o.select :player, options_for_select(characterNames, selected = nil)
        Player
        Opponent
        = o.select :opponent, options_for_select(characterNames, selected = nil)
      %p
        = o.text_area :body
        = o.submit "Submit", :action => :create, :class => :button

app/views/tips/show.haml
%h1
  .bigSpacer= link_to image_tag("../img/characters/#{tip.player}.jpg"), character_show_path(tip.player) 
  .bigSpacer= link_to image_tag("../img/characters/#{tip.opponent}.jpg"), character_show_path(tip.opponent)
  %br
  .spacer=tip.player
  =image_tag("../img/vs.png", :height => "10%", :margin => "50px 0")
  .spacer=tip.opponent
#section2
  #tip
    %p
      - unless tip.user.admin
        = image_tag("/img/quotes-open.png")
        =tip.body
        = image_tag("/img/quotes-close.png")
      - else
        = image_tag("/img/quotes-open.png")
        =raw(tip.body)
        = image_tag("/img/quotes-close.png")
      %b
        = tip.user.name
        = ':'
        = time_ago_in_words(tip.created_at)
        ago
#comments
  %h2 Comments
  %hr
  <div id="fb-root"></div><script src="http://connect.facebook.net/en_US/all.js#xfbml=1"></script><fb:comments href="matchuptips.com/tips/#{tip.id}" num_posts="5" width="550"></fb:comments>
%h2 
#section2
  - unless characterTips.empty?
    %h2
      More!
    %hr
    %ul.tips
      - characterTips.each do |tip|
        %li
          %h3
            = link_to tip.player, character_show_path(tip.player)
            = link_to image_tag("../img/characters/#{tip.player}.jpg"), character_show_path(tip.player)
            VS
            = link_to image_tag("../img/characters/#{tip.opponent}.jpg"), character_show_path(tip.opponent)
            = link_to tip.opponent, character_show_path(tip.opponent)
          %p=link_to truncate(tip.body, :length => 150, :omission => "....."), tip_path(tip)
          .userName= tip.user.name
          = ':'
          = time_ago_in_words(tip.created_at)
          ago

app/views/users/index.haml
- if current_user && current_user.admin
  %h1 
    Users
    = users.count
    %hr
  %ul
    - users.each do |user|
      %li
        = user.name
- else
  %h2 NICE TRY NON ADMIN PERSON!